New Python versions in tests
fedora-python/tox-current-env pull request #49
Opened 2022-02-09 09:29 UTC by frenzymadness

I've used this as an exercise to understand the tests and now I'm gonna try to rewrite them for tox 4.

2022-02-09 09:56 UTC, hroncok requested changes
Could you please change https://github.com/fedora-python/tox-current-env#tests and https://github.com/fedora-python/tox-current-env/blob/master/setup.py#L36 as well?

2022-02-10 10:28 UTC, frenzymadness commented
> Could you please change https://github.com/fedora-python/tox-current-env#tests and https://github.com/fedora-python/tox-current-env/blob/master/setup.py#L36 as well?

Done.

I'm gonna limit this PR to Python 3.10 only. My plan is to redefine the tests in #42 so adding the next Python will be much easier.

2022-02-10 10:38 UTC, frenzymadness commented
All green, finally!

2022-02-10 11:02 UTC, hroncok approved these changes

2022-02-10 12:17 UTC, merged

2022-02-18 18:44 UTC, hroncok commented on .github/workflows/main.yaml
> +        - py310-toxtox315
I have not spotted that this is a bug in tox configuration. Now we don't test with tox 3.15 at all.  Fix included in https://github.com/fedora-python/tox-current-env/pull/47